# Generated by Django 2.0.6 on 2018-06-21 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockapp', '0003_blocktable_isprivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('authId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockapp.Blocktable')),
            ],
        ),
    ]
